# -*- coding: utf-8 -*-
"""solarproject1234.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLo31AvjKkxAnk02S5l1ZtdZ04A-qbLw
"""

import streamlit as st
import numpy as np
import joblib
import pandas as pd

# Load model & scaler
model = joblib.load("solar_model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("☀️ Solar Panel Power Predictor")

st.write("Enter weather and panel parameters:")

# Input fields
azimuth = st.number_input("Azimuth", 0, 360, 180)
zenith = st.number_input("Zenith", 0, 90, 30)
angle_of_incidence = st.number_input("Angle of Incidence", 0, 90, 25)
wind_speed = st.number_input("Wind Speed (m/s)", 0.0, 20.0, 3.0)
high_cloud = st.number_input("High Cloud Cover", 0, 100, 20)
low_cloud = st.number_input("Low Cloud Cover", 0, 100, 10)

input_data = np.array([[azimuth, zenith, angle_of_incidence,
                        wind_speed, high_cloud, low_cloud]])

if st.button("Predict Power"):
    scaled = scaler.transform(input_data)
    prediction = model.predict(scaled)
    st.success(f"🔋 Predicted Solar Power: {prediction[0]:.2f} kW")



