# -*- coding: utf-8 -*-
"""solarproject1234.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLo31AvjKkxAnk02S5l1ZtdZ04A-qbLw
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

import joblib

df = pd.read_csv("spg.csv.csv")
df.head()

df.info()

df.columns

df.isnull().sum()

df.fillna(df.mean(), inplace=True)

X = df.drop("generated_power_kw", axis=1)
y = df["generated_power_kw"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

plt.figure(figsize=(14,10))
sns.heatmap(df.corr(), cmap="coolwarm", annot=False)
plt.title("Feature Correlation Heatmap")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df["generated_power_kw"], bins=30, kde=True)
plt.title("Generated Power Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(x=df["high_cloud_cover_high_cld_lay"], y=df["generated_power_kw"])
plt.title("High Cloud Cover vs Generated Power")
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(df["wind_speed_10_m_above_gnd"], df["generated_power_kw"])
plt.xlabel("wind_speed")
plt.ylabel("Generated Power")
plt.title("Wind Speed vs Generated Power")
plt.show()

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

importance = model.feature_importances_
features = X.columns

imp_df = pd.DataFrame({
    "Feature": features,
    "Importance": importance
}).sort_values(by="Importance", ascending=False)

imp_df

plt.figure(figsize=(8,6))
sns.barplot(x=imp_df["Importance"], y=imp_df["Feature"])
plt.title("Feature Importance")
plt.show()







import joblib
import numpy as np
import os

base_path = "/content/drive/MyDrive/solar_project"

model = joblib.load(os.path.join(base_path, "solar_model.pkl"))
scaler = joblib.load(os.path.join(base_path, "scaler.pkl"))

print("Model & scaler loaded successfully!")

FEATURE_NAMES = [
    "azimuth",
    "zenith",
    "angle_of_incidence",
    "wind_gust",
    "wind_direction",
    "wind_speed",
    "high_cloud_cover",
    "medium_cloud_cover",
    "low_cloud_cover",
    "snowfall_amount",
    "total_precipitation",
    "mean_sea_level",
    "relative_humidity"
]

def predict_solar_power(input_data):
    """
    input_data: dict with feature names as keys
    returns: predicted generated power
    """

    # Convert dict → array in correct order
    input_array = np.array([[input_data[feature] for feature in FEATURE_NAMES]])

    # Scale input
    input_scaled = scaler.transform(input_array)

    # Predict
    prediction = model.predict(input_scaled)

    return float(prediction[0])

sample_input = {
    "azimuth": 180,
    "zenith": 40,
    "angle_of_incidence": 25,

    "wind_speed": 3.5,
    "wind_gust": 6.2,
    "wind_direction": 270,

    "high_cloud_cover": 15,
    "medium_cloud_cover": 30,
    "low_cloud_cover": 10,

    "relative_humidity": 55,
    "mean_sea_level": 1012,
    "surface_pressure": 1008,
    "air_temperature": 32,
    "dew_point": 18,

    "total_precipitation": 0,
    "snowfall_amount": 0,
    "rainfall_amount": 0,

    "solar_irradiance": 820,
    "visibility": 10
}

predicted_power = predict_solar_power(sample_input)
print("Predicted Solar Power:", predicted_power)

feature_names = X.columns.tolist()



import joblib
import pandas as pd

model = joblib.load(f"{base_path}/solar_model.pkl")
scaler = joblib.load(f"{base_path}/scaler.pkl")
feature_names = joblib.load(f"{base_path}/features.pkl")

sample_input = {
    "azimuth": 180,
    "zenith": 30,
    "angle_of_incidence": 25,
    "wind_gust_10_m_above_gnd": 5,
    "wind_direction_10_m_above_gnd": 120,
    "wind_speed_10_m_above_gnd": 3,
    "high_cloud_cover_high_cld_lay": 20,
    "medium_cloud_cover_mid_cld_lay": 10,
    "low_cloud_cover_low_cld_lay": 5,
    "snowfall_amount_sfc": 0,
    "total_precipitation_sfc": 0,
    "mean_sea_level_pressure_MSL": 1012,
    "relative_humidity_2_m_above_gnd": 60,
    "solar_irradiance": 820,
    "visibility": 10,
    "temperature_2_m_above_gnd":45,
    "total_cloud_cover_sfc":20,
    "shortwave_radiation_backwards_sfc":450,
    "wind_speed_80_m_above_gnd":45,
    "wind_direction_80_m_above_gnd":30,
    "wind_speed_900_mb":50,
    "wind_direction_900_mb":40
}

input_df = pd.DataFrame([sample_input])
input_df = input_df[feature_names]   # 🔥 ensures correct order

input_scaled = scaler.transform(input_df)
predicted_power = model.predict(input_scaled)

print("Predicted Solar Power:", predicted_power[0])



